=== Ogi22po/legal/legal/knr/static/knr-1.7.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Schema for KNR V1.7 <https://legal.pecina.cz/> -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://legal.pecina.cz" xmlns="http://legal.pecina.cz" elementFormDefault="qualified">
  <xs:element name="calculation">
    <xs:complexType>
      <xs:sequence>
	<xs:element name="title" type="xs:token"/>
	<xs:element name="calculation_note" type="xs:string"/>
	<xs:element name="internal_note" type="xs:string"/>
	<xs:element name="vat_rate">
	  <xs:complexType>
	    <xs:simpleContent>
	      <xs:extension base="nonNegativeDecimal">
		<xs:attribute name="unit" use="required" type="xs:NCName" fixed="percentage"/>
	      </xs:extension>
	    </xs:simpleContent>
	  </xs:complexType>
	</xs:element>
	<xs:element ref="items"/>
      </xs:sequence>
      <xs:attribute name="version" use="required" type="xs:NMTOKEN" fixed="1.7"/>
      <xs:attribute name="application" use="required" type="xs:NCName" fixed="knr"/>
      <xs:attribute name="created" use="required" type="xs:dateTime"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="nonNegativeDecimal">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="boolean">
    <xs:restriction base="xs:NCName">
      <xs:enumeration value="false"/>
      <xs:enumeration value="true"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="amount">
    <xs:simpleContent>
      <xs:extension base="nonNegativeDecimal">
	<xs:attribute name="currency" use="required" type="xs:NCName" fixed="CZK"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="geo">
    <xs:simpleContent>
      <xs:extension base="xs:decimal">
	<xs:attribute name="unit" use="required" type="xs:NCName" fixed="deg"/>
	<xs:attribute name="datum" use="required" type="xs:NCName" fixed="WGS84"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="lat">
    <xs:simpleContent>
      <xs:restriction base="geo">
	<xs:minInclusive value="-90"/>
	<xs:maxInclusive value="90"/>
      </xs:restriction>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="lon">
    <xs:simpleContent>
      <xs:restriction base="geo">
	<xs:minInclusive value="-180"/>
	<xs:maxInclusive value="180"/>
      </xs:restriction>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="cons">
    <xs:simpleContent>
      <xs:extension base="nonNegativeDecimal">
	<xs:attribute name="unit" use="required" type="xs:token" fixed="l per 100 km"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:element name="items">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
	<xs:choice>
	  <xs:element ref="general"/>
	  <xs:element ref="service"/>
	  <xs:element ref="flat"/>
	  <xs:element ref="administrative"/>
	  <xs:element ref="time"/>
	  <xs:element ref="travel"/>
	</xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="general">
    <xs:complexType>
      <xs:sequence>
	<xs:element ref="description"/>
	<xs:element ref="amount"/>
	<xs:element ref="vat"/>
	<xs:element ref="numerator"/>
	<xs:element ref="denominator"/>
	<xs:element ref="item_note"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="service">
    <xs:complexType>
      <xs:sequence>
	<xs:element ref="description"/>
	<xs:element ref="amount"/>
	<xs:element ref="vat"/>
	<xs:element ref="numerator"/>
	<xs:element ref="denominator"/>
	<xs:element ref="item_note"/>
	<xs:element ref="major_number"/>
	<xs:element ref="rate"/>
	<xs:element ref="minor_number"/>
	<xs:element ref="multiple_number"/>
	<xs:element ref="off10_flag"/>
	<xs:element ref="off30_flag"/>
	<xs:element ref="off30limit5000_flag"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="flat">
    <xs:complexType>
      <xs:sequence>
	<xs:element ref="description"/>
	<xs:element ref="amount"/>
	<xs:element ref="vat"/>
	<xs:element ref="numerator"/>
	<xs:element ref="denominator"/>
	<xs:element ref="rate"/>
	<xs:element ref="multiple_flag"/>
	<xs:element ref="multiple50_flag"/>
	<xs:element ref="item_note"/>
	<xs:element ref="single_flag"/>
	<xs:element ref="halved_flag"/>
	<xs:element ref="halved_appeal_flag"/>
	<xs:element ref="collection_flag"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="administrative">
    <xs:complexType>
      <xs:sequence>
	<xs:element ref="description"/>
	<xs:element ref="amount"/>
	<xs:element ref="vat"/>
	<xs:element ref="numerator"/>
	<xs:element ref="denominator"/>
	<xs:element ref="item_note"/>
	<xs:element ref="number"/>
	<xs:element ref="rate"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="time">
    <xs:complexType>
      <xs:sequence>
	<xs:element ref="description"/>
	<xs:element ref="amount"/>
	<xs:element ref="vat"/>
	<xs:element ref="numerator"/>
	<xs:element ref="denominator"/>
	<xs:element ref="item_note"/>
	<xs:element ref="time_number"/>
	<xs:element ref="time_rate"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="travel">
    <xs:complexType>
      <xs:sequence>
	<xs:element ref="description"/>
	<xs:element ref="amount"/>
	<xs:element ref="vat"/>
	<xs:element ref="numerator"/>
	<xs:element ref="denominator"/>
	<xs:element ref="item_note"/>
	<xs:element ref="from_name"/>
	<xs:element ref="from_address"/>
	<xs:element ref="from_lat"/>
	<xs:element ref="from_lon"/>
	<xs:element ref="to_name"/>
	<xs:element ref="to_address"/>
	<xs:element ref="to_lat"/>
	<xs:element ref="to_lon"/>
	<xs:element ref="trip_number"/>
	<xs:element ref="trip_distance"/>
	<xs:element ref="time_rate"/>
	<xs:element ref="time_number"/>
	<xs:element ref="car_name"/>
	<xs:element ref="fuel_name"/>
	<xs:element ref="cons1"/>
	<xs:element ref="cons2"/>
	<xs:element ref="cons3"/>
	<xs:element ref="formula_name"/>
	<xs:element ref="flat_rate"/>
	<xs:element ref="fuel_price"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="description" type="xs:token"/>
  <xs:element name="amount" type="amount"/>
  <xs:element name="vat" type="boolean"/>
  <xs:element name="numerator" type="xs:positiveInteger"/>
  <xs:element name="denominator" type="xs:positiveInteger"/>
  <xs:element name="item_note" type="xs:string"/>
  <xs:element name="major_number" type="xs:nonNegativeInteger"/>
  <xs:element name="rate" type="amount"/>
  <xs:element name="minor_number" type="xs:nonNegativeInteger"/>
  <xs:element name="multiple_number" type="xs:nonNegativeInteger"/>
  <xs:element name="off10_flag" type="boolean"/>
  <xs:element name="off30_flag" type="boolean"/>
  <xs:element name="off30limit5000_flag" type="boolean"/>
  <xs:element name="multiple_flag" type="boolean"/>
  <xs:element name="multiple50_flag" type="boolean"/>
  <xs:element name="single_flag" type="boolean"/>
  <xs:element name="halved_flag" type="boolean"/>
  <xs:element name="halved_appeal_flag" type="boolean"/>
  <xs:element name="collection_flag" type="boolean"/>
  <xs:element name="number" type="xs:nonNegativeInteger"/>
  <xs:element name="time_number">
    <xs:complexType>
      <xs:simpleContent>
	<xs:extension base="xs:nonNegativeInteger">
	  <xs:attribute name="unit" use="required" type="xs:NCName" fixed="half-hour"/>
	</xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="time_rate">
    <xs:complexType>
      <xs:simpleContent>
	<xs:extension base="amount">
	  <xs:attribute name="unit" use="required" type="xs:token" fixed="per half-hour"/>
	</xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="from_name" type="xs:token"/>
  <xs:element name="from_address" type="xs:token"/>
  <xs:element name="from_lat" type="lat"/>
  <xs:element name="from_lon" type="lon"/>
  <xs:element name="to_name" type="xs:token"/>
  <xs:element name="to_address" type="xs:token"/>
  <xs:element name="to_lat" type="lat"/>
  <xs:element name="to_lon" type="lon"/>
  <xs:element name="trip_number" type="xs:nonNegativeInteger"/>
  <xs:element name="trip_distance">
    <xs:complexType>
      <xs:simpleContent>
	<xs:extension base="nonNegativeDecimal">
	  <xs:attribute name="unit" use="required" type="xs:NCName" fixed="km"/>
	</xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="car_name" type="xs:token"/>
  <xs:element name="fuel_name" type="xs:NCName"/>
  <xs:element name="cons1" type="cons"/>
  <xs:element name="cons2" type="cons"/>
  <xs:element name="cons3" type="cons"/>
  <xs:element name="formula_name" type="xs:token"/>
  <xs:element name="flat_rate">
    <xs:complexType>
      <xs:simpleContent>
	<xs:extension base="amount">
	  <xs:attribute name="unit" use="required" type="xs:token" fixed="per km"/>
	</xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="fuel_price">
    <xs:complexType>
      <xs:simpleContent>
	<xs:extension base="amount">
	  <xs:attribute name="unit" use="required" type="xs:token" fixed="per l"/>
	</xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Ogi22po/legal/knr/testdata/calc1.xml
<?xml version="1.0" encoding="utf-8"?>
<calculation application="knr" created="2016-07-08T00:11:18" version="1.7" xmlns="http://legal.pecina.cz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://legal.pecina.cz https://legal.pecina.cz/static/knr-1.7.xsd"><title>Příliš žluťoučký kůň úpěnlivě přepíná ďábelské kódy</title><calculation_note>Poznámka</calculation_note><internal_note>Interní poznámka</internal_note><vat_rate unit="percentage">21.00</vat_rate><items><general><description>Zaplacený soudní poplatek</description><amount currency="CZK">300</amount><vat>false</vat><numerator>2</numerator><denominator>3</denominator><item_note>Poznámka</item_note></general><general><description>Zaplacená záloha na znalecký posudek</description><amount currency="CZK">2000</amount><vat>false</vat><numerator>2</numerator><denominator>3</denominator><item_note></item_note></general><general><description>Zaplacená záloha na svědečné</description><amount currency="CZK">826</amount><vat>false</vat><numerator>2</numerator><denominator>3</denominator><item_note></item_note></general><travel><description>Náhrada za použití motorového vozidla (klient)</description><amount currency="CZK">1241</amount><vat>false</vat><numerator>2</numerator><denominator>3</denominator><item_note></item_note><from_name>Krajský soud v Brně</from_name><from_address>Rooseveltova 648/16, 602 00 Brno, Česká republika</from_address><from_lat datum="WGS84" unit="deg">49.1967243</from_lat><from_lon datum="WGS84" unit="deg">16.6119663</from_lon><to_name>Krajský soud v Brně, pobočka v Jihlavě</to_name><to_address>tř. Legionářů 5277/9a, 586 01 Jihlava, Česká republika</to_address><to_lat datum="WGS84" unit="deg">49.4011190</to_lat><to_lon datum="WGS84" unit="deg">15.5845102</to_lon><trip_number>2</trip_number><trip_distance unit="km">94</trip_distance><time_rate currency="CZK" unit="per half-hour">0</time_rate><time_number unit="half-hour">3</time_number><car_name>Zkušební vozidlo</car_name><fuel_name>NM</fuel_name><cons1 unit="l per 100 km">11.9</cons1><cons2 unit="l per 100 km">7.5</cons2><cons3 unit="l per 100 km">9.1</cons3><formula_name>Vyhláška č. 385/2015 Sb.</formula_name><flat_rate currency="CZK" unit="per km">3.80</flat_rate><fuel_price currency="CZK" unit="per l">29.50</fuel_price></travel><general><description>Další hotové výdaje (klient)</description><amount currency="CZK">28</amount><vat>false</vat><numerator>2</numerator><denominator>3</denominator><item_note></item_note></general><service><description>Mimosmluvní odměna za úkony právní služby podle advokátního tarifu</description><amount currency="CZK">8100</amount><vat>false</vat><numerator>2</numerator><denominator>3</denominator><item_note></item_note><major_number>5</major_number><rate currency="CZK">1620</rate><minor_number>0</minor_number><multiple_number>1</multiple_number><off10_flag>false</off10_flag><off30_flag>false</off30_flag><off30limit5000_flag>false</off30limit5000_flag></service><flat><description>Paušální odměna za zastupování účastníka podle vyhlášky č. 484/2000 Sb.</description><amount currency="CZK">400</amount><vat>false</vat><numerator>2</numerator><denominator>3</denominator><rate currency="CZK">1500</rate><multiple_flag>false</multiple_flag><multiple50_flag>false</multiple50_flag><item_note></item_note><single_flag>true</single_flag><halved_flag>true</halved_flag><halved_appeal_flag>false</halved_appeal_flag><collection_flag>false</collection_flag></flat><general><description>Paušální odměna za zastupování účastníka stanovená pevnou částkou</description><amount currency="CZK">500</amount><vat>false</vat><numerator>2</numerator><denominator>3</denominator><item_note></item_note></general><travel><description>Náhrada za použití motorového vozidla (advokát)</description><amount currency="CZK">1841</amount><vat>false</vat><numerator>2</numerator><denominator>3</denominator><item_note></item_note><from_name>Krajský soud v Brně</from_name><from_address>Rooseveltova 648/16, 602 00 Brno, Česká republika</from_address><from_lat datum="WGS84" unit="deg">49.1967243</from_lat><from_lon datum="WGS84" unit="deg">16.6119663</from_lon><to_name>Krajský soud v Brně, pobočka v Jihlavě</to_name><to_address>tř. Legionářů 5277/9a, 586 01 Jihlava, Česká republika</to_address><to_lat datum="WGS84" unit="deg">49.4011190</to_lat><to_lon datum="WGS84" unit="deg">15.5845102</to_lon><trip_number>2</trip_number><trip_distance unit="km">94</trip_distance><time_rate currency="CZK" unit="per half-hour">100</time_rate><time_number unit="half-hour">3</time_number><car_name>Zkušební vozidlo</car_name><fuel_name>NM</fuel_name><cons1 unit="l per 100 km">11.9</cons1><cons2 unit="l per 100 km">7.5</cons2><cons3 unit="l per 100 km">9.1</cons3><formula_name>Vyhláška č. 385/2015 Sb.</formula_name><flat_rate currency="CZK" unit="per km">3.80</flat_rate><fuel_price currency="CZK" unit="per l">29.50</fuel_price></travel><time><description>Náhrada za promeškaný čas podle advokátního tarifu</description><amount currency="CZK">400</amount><vat>false</vat><numerator>2</numerator><denominator>3</denominator><item_note></item_note><time_number unit="half-hour">4</time_number><time_rate currency="CZK" unit="per half-hour">100</time_rate></time><administrative><description>Paušální náhrada za úkony právní služby podle advokátního tarifu</description><amount currency="CZK">900</amount><vat>false</vat><numerator>2</numerator><denominator>3</denominator><item_note></item_note><number>3</number><rate currency="CZK">300</rate></administrative><general><description>Další hotové výdaje (advokát)</description><amount currency="CZK">700</amount><vat>false</vat><numerator>2</numerator><denominator>3</denominator><item_note></item_note></general><service><description>Mimosmluvní odměna za úkony právní služby podle advokátního tarifu</description><amount currency="CZK">29500</amount><vat>true</vat><numerator>2</numerator><denominator>3</denominator><item_note></item_note><major_number>4</major_number><rate currency="CZK">5900</rate><minor_number>2</minor_number><multiple_number>1</multiple_number><off10_flag>false</off10_flag><off30_flag>false</off30_flag><off30limit5000_flag>false</off30limit5000_flag></service><flat><description>Paušální odměna za zastupování účastníka podle vyhlášky č. 484/2000 Sb.</description><amount currency="CZK">36070</amount><vat>true</vat><numerator>2</numerator><denominator>3</denominator><rate currency="CZK">36070</rate><multiple_flag>false</multiple_flag><multiple50_flag>false</multiple50_flag><item_note></item_note><single_flag>false</single_flag><halved_flag>false</halved_flag><halved_appeal_flag>false</halved_appeal_flag><collection_flag>false</collection_flag></flat><general><description>Paušální odměna za zastupování účastníka stanovená pevnou částkou</description><amount currency="CZK">900</amount><vat>true</vat><numerator>2</numerator><denominator>3</denominator><item_note></item_note></general><travel><description>Náhrada za použití motorového vozidla (advokát)</description><amount currency="CZK">1841</amount><vat>true</vat><numerator>2</numerator><denominator>3</denominator><item_note></item_note><from_name>Krajský soud v Brně</from_name><from_address>Rooseveltova 648/16, 602 00 Brno, Česká republika</from_address><from_lat datum="WGS84" unit="deg">49.1967243</from_lat><from_lon datum="WGS84" unit="deg">16.6119663</from_lon><to_name>Krajský soud v Brně, pobočka v Jihlavě</to_name><to_address>tř. Legionářů 5277/9a, 586 01 Jihlava, Česká republika</to_address><to_lat datum="WGS84" unit="deg">49.4011190</to_lat><to_lon datum="WGS84" unit="deg">15.5845102</to_lon><trip_number>2</trip_number><trip_distance unit="km">94</trip_distance><time_rate currency="CZK" unit="per half-hour">100</time_rate><time_number unit="half-hour">3</time_number><car_name>Zkušební vozidlo</car_name><fuel_name>NM</fuel_name><cons1 unit="l per 100 km">11.9</cons1><cons2 unit="l per 100 km">7.5</cons2><cons3 unit="l per 100 km">9.1</cons3><formula_name>Vyhláška č. 385/2015 Sb.</formula_name><flat_rate currency="CZK" unit="per km">3.80</flat_rate><fuel_price currency="CZK" unit="per l">29.50</fuel_price></travel><time><description>Náhrada za promeškaný čas podle advokátního tarifu</description><amount currency="CZK">700</amount><vat>true</vat><numerator>2</numerator><denominator>3</denominator><item_note></item_note><time_number unit="half-hour">7</time_number><time_rate currency="CZK" unit="per half-hour">100</time_rate></time><administrative><description>Paušální náhrada za úkony právní služby podle advokátního tarifu</description><amount currency="CZK">1800</amount><vat>true</vat><numerator>2</numerator><denominator>3</denominator><item_note></item_note><number>6</number><rate currency="CZK">300</rate></administrative><general><description>Další hotové výdaje (advokát)</description><amount currency="CZK">1430</amount><vat>true</vat><numerator>2</numerator><denominator>3</denominator><item_note></item_note></general></items></calculation>

=== Ogi22po/legal/knr/testdata/calc4.xml
<?xml version="1.0" encoding="utf-8"?>
<calculation application="knr" created="2016-07-08T01:33:06" version="1.4" xmlns="http://legal.pecina.cz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://legal.pecina.cz https://legal.pecina.cz/static/knr-1.7.xsd"><title></title><calculation_note></calculation_note><internal_note></internal_note><vat_rate unit="percentage">10.00</vat_rate><items><service><description>Mimosmluvní odměna za úkony právní služby podle advokátního tarifu</description><amount currency="CZK">20000</amount><vat>false</vat><numerator>2</numerator><denominator>3</denominator><item_note></item_note><major_number>10</major_number><rate currency="CZK">1000</rate><minor_number>20</minor_number><multiple_number>1</multiple_number><off10_flag>false</off10_flag><off30_flag>false</off30_flag><off30limit5000_flag>false</off30limit5000_flag></service><administrative><description>Paušální náhrada za úkony právní služby podle advokátního tarifu</description><amount currency="CZK">3000</amount><vat>true</vat><numerator>2</numerator><denominator>3</denominator><item_note></item_note><number>10</number><rate currency="CZK">300</rate></administrative><travel><description>Náhrada za použití motorového vozidla (advokát)</description><amount currency="CZK">1200</amount><vat>true</vat><numerator>2</numerator><denominator>3</denominator><item_note></item_note><from_name>Krajský soud v Brně</from_name><from_address>Rooseveltova 648/16, 602 00 Brno, Česká republika</from_address><from_lat datum="WGS84" unit="deg">49.1967243</from_lat><from_lon datum="WGS84" unit="deg">16.6119663</from_lon><to_name>Krajský soud v Brně, pobočka v Jihlavě</to_name><to_address>tř. Legionářů 5277/9a, 586 01 Jihlava, Česká republika</to_address><to_lat datum="WGS84" unit="deg">49.4011190</to_lat><to_lon datum="WGS84" unit="deg">15.5845102</to_lon><trip_number>1</trip_number><trip_distance unit="km">100</trip_distance><time_rate currency="CZK" unit="per half-hour">100</time_rate><time_number unit="half-hour">10</time_number><car_name>Zkušební vozidlo</car_name><fuel_name>NM</fuel_name><cons1 unit="l per 100 km">10.0</cons1><cons2 unit="l per 100 km">10.0</cons2><cons3 unit="l per 100 km">10.0</cons3><formula_name>Vyhláška č. 385/2015 Sb.</formula_name><flat_rate currency="CZK" unit="per km">1.00</flat_rate><fuel_price currency="CZK" unit="per l">10.00</fuel_price></travel></items></calculation>
